"""Add the subscribers table

Revision ID: 554318b4b7af
Revises: 119b44f3bc18
Create Date: 2018-11-25 17:37:56.355735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554318b4b7af'
down_revision = '119b44f3bc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
